# Please make sure you run the following permission command: 
# chmod 777 -R /data/artifactory

version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.17.0
    container_name: artifactory
    ports:
     - 80:8081
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

